### ISSUE TITLE
Raceroom not working

### ISSUE THREAD

**Issue by jordanpucela** [fholger/openvr_fsr#11] opened 2021-07-08 18:12 UTC
One of the games that the FSR awaits the most is the RaceRoom and it gives an error when starting. I copy you the log that lets you see if you know the error.
Thank you for your work.
Log:
Initializing hooks ...
Requested interface IVRSystem_012
Injecting GetRecommendedRenderTargetSize into IVRSystem_012
Requested interface IVRRenderModels_005
Requested interface IVRCompositor_016
Injecting Submit into IVRCompositor_016

**Comment by Jabbah** [comment] 2021-07-09 20:02
RaceRoom is DX9 so isn't supported yet, only DX11 games so far.

**Comment by fholger** [comment] 2021-07-09 20:15
OpenVR does not support DX9. If the game really does render with DX9, it has to go through some translation layer to another API before submission. If that's not DX11, then yeah, it would not be supported.

**Comment by Jabbah** [comment] 2021-07-09 21:35
Yeah it's a DX9 only game. I did hear they had to do some interesting stuff to get it working in VR so that must be why. I've got it so I'll have a dig and see if I can see what's going on.

**Comment by Davizmg** [comment] 2021-08-23 23:37
Hi,raceroom in vr works on dx10 not in dx9, if you make compatible the openvr_fsr with dx10 then works

**Comment by fholger** [comment] 2021-08-24 06:33
It doesn't matter what Raceroom renders with internally, it only matters what it submits to OpenVR. And since OpenVR does not support DX9 or DX10, it has to submit DX11 textures. That's not the reason why this doesn't work with Raceroom.

**Comment by retroluxfilm** [comment] 2021-08-24 17:40
Yes Raceroom uses DX10 to submit to openVR. Yesterday i could add that functionality to reshade to get Race Room Working. Should be not that difficult to get it ready for openvr_fsr. The only difference is that instead on the device context it must be worked on the device itself. The tricky part though is to find out if it is DX11 or DX10 as the VR compositor does not have a distiction between them. You can look at the reshade implementation here: https://github.com/retroluxfilm/reshade/commit/78a87cf77d9e3b19f750526abf98773d57ff10db

**Comment by fholger** [comment] 2021-08-24 18:16
I stand corrected, thanks.

However, that alone doesn't really help. FSR is a Shader Model 5 compute shader and, to my knowledge, can't operate in D3D10, directly. So we'd need to deal with an incoming D3D10 texture, which would require adding quite a bit of foundation work, and then share it with a D3D11 system that we'd have to setup ourselves only to get the FSR pass working. I'll happily let someone else prove me wrong, but for me that sounds like an absurd level of complexity to enable a single game, so I'm afraid I'm going to pass on this.

**Comment by retroluxfilm** [comment] 2021-08-24 18:35
It might be easier for FSR to try to switch the device context from DX10 to DX11.
https://docs.microsoft.com/en-us/windows/win32/api/d3d11_1/nf-d3d11_1-id3d11devicecontext1-swapdevicecontextstate

Check out the hybrid compositor from Vytas that does this as well: https://gitlab.com/TheIronWolfModding/OpenOVR/-/blob/master/OpenOVR/Compositor/dx11hybridcompositor.cpp

Hope that can be of any help in case you want to look into it or someone else wants to tackle this :)

**Comment by fholger** [comment] 2021-08-24 18:42
If someone wants to implement this and submit a pull request, I'll consider it, as long as the added complexity is not too high. But for now, I'm going to close this issue - the mod is specifically targeted at DX11 OpenVR games, and now that it is clear that RaceRoom is not in that category, it is not a bug for it to not be working.

**Closed as completed by fholger** 2021-08-24 18:42 UTC
