### ISSUE TITLE
Double vision in IL2

### ISSUE THREAD

**Issue by dirtymike0330** [fholger/openvr_fsr#4] opened 2021-07-07 14:17 UTC
Trying this mod in IL2, it caused a very harsh distortion in my view, almost like a double vision issue. Did not happen when testing in DCS with the same installation process and leaving the mod cfg file as default. 

HP Reverb G2

**Comment by DTA666-sys** [comment] 2021-07-08 16:21
Same. Anyone found a fix yet?

**Comment by fholger** [comment] 2021-07-08 17:06
Duplicate of #3

**Closed as completed by fholger** 2021-07-08 17:06 UTC
